### ISSUE TITLE
Truncate the title of topics for style like prosilver SE

### ISSUE THREAD

**Issue by Galixte** [RMcGirr83/phpBB-3.1-topfive#10]
Hi @RMcGirr83,

in some cases with styles like prosilver SE and other styles with the same width, if the title of topics
is longer than usual the title will be over the “Top Active Users” column, and even the “Newest Users” column.

Could you fix this, please ?

**Comment by RMcGirr83** [comment]
I can't be expected to support every style out there.  How would you suggest I check for the width?

**Comment by Galixte** [comment]
The extension with displaying similar of yours is Recent Topics by Paysbas: https://github.com/PayBas/RecentTopics maybe you take a look here: https://github.com/PayBas/RecentTopics/tree/master/styles/all/template.

Or maybe this other issue will help you to resolve this problem: https://github.com/board3/Board3-Portal/pull/609.

**Comment by RMcGirr83** [comment]
Can you show me a link where the topic title is going over?

**Comment by RMcGirr83** [comment]
See if this does it
https://github.com/RMcGirr83/phpBB-3.1-topfive/commit/c3cdf3efdf125a09d0ce7d9894d5e2d124f9b630

**Comment by Galixte** [comment]
Yes ! Thanks it’s better, i propose you juste toplace the forum source link at the end, after of author post and date:https://github.com/RMcGirr83/phpBB-3.1-topfive/pull/11.
