### ISSUE TITLE
Top Five v1.04 drops mobile support

### ISSUE THREAD

**Issue by bcurran3** [rmcgirr83/phpBB-3.1-topfive#18]
My mobile users can't see the Top Five / NEWEST POSTS. I have confirmed.

Bug?
Intentional?

p.s. I have everything sent to top ten.
(I doubt there's a relation, but just in case, throwing it out there!)

**Comment by rmcgirr83** [comment]
Pretty sure it is coded that way intentionally.  It shouldn't be difficult to have just the newest posts display when on mobile.

**Comment by bcurran3** [comment]
It used to work for mobile. :)

**Comment by rmcgirr83** [comment]
https://www.phpbb.com/customise/db/extension/topfiveext/support/topic/164061
