### ISSUE TITLE
Error "BACKTRACE"

### ISSUE THREAD

**Issue by cavive** [rmcgirr83/phpBB-3.1-topfive#22]
FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 852
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/mysql_base.php
LINE: 45
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 261
CALL: phpbb\db\driver\mysql_base->_sql_query_limit()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 321
CALL: phpbb\db\driver\driver->sql_query_limit()

FILE: [ROOT]/ext/rmcgirr83/topfive/core/topfive.php
LINE: 88
CALL: phpbb\db\driver\factory->sql_query_limit()

FILE: [ROOT]/ext/rmcgirr83/topfive/event/listener.php
LINE: 62
CALL: rmcgirr83\topfive\core\topfive->toptopics()

FILE: (not given by php)
LINE: (not given by php)
CALL: rmcgirr83\topfive\event\listener->main()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 161
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/includes/functions.php
LINE: 5445
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/viewforum.php
LINE: 170
CALL: page_footer()

**Comment by rmcgirr83** [comment]
Need more information like 1) how did you install the extension 2) what version of PHP and 3) what version of phpBB?

**Comment by cavive** [comment]
Hello

I install the Ext using this > Upload Extensions - forumhulp
- PHP Version 5.5.9-1ubuntu4.20
- Current version phpBB3.1.10

-- its hard for me to explain, but will try.
I am using this extension months ago, and sometimes I get that error when reloding /viewforum.

**Comment by rmcgirr83** [comment]
Then don't use that extension to install it

**Comment by cavive** [comment]
Got another one, just now.

 
BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/auth/auth.php
LINE: 634
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/auth/auth.php
LINE: 388
CALL: phpbb\auth\auth->acl_raw_data()

FILE: [ROOT]/ext/rmcgirr83/topfive/core/topfive.php
LINE: 223
CALL: phpbb\auth\auth->acl_get_list()

FILE: [ROOT]/ext/rmcgirr83/topfive/event/listener.php
LINE: 60
CALL: rmcgirr83\topfive\core\topfive->topposters()

FILE: (not given by php)
LINE: (not given by php)
CALL: rmcgirr83\topfive\event\listener->main()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 161
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/includes/functions.php
LINE: 5445
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/viewforum.php
LINE: 170
CALL: page_footer()

**Comment by cavive** [comment]
> Then don't use that extension to install it

> Upload Extensions - forumhulp

This extension is bad?

**Comment by rmcgirr83** [comment]
I don't know I don't use it. Uninstall th is extension, delete the data and reinstall. This extension doesn't use any events in viewforum
