### ISSUE TITLE
Master branch for 3.1.x version of phpBB

### ISSUE THREAD

**Issue by Galixte** [rmcgirr83/phpBB-3.1-topfive#23]
Hi @rmcgirr83,

is the 1.1.1 version is dedicated to phpBB 3.2.x or it can be used with 3.1.x branch of phpBB ?

I ask you this because on the official page, here: https://www.phpbb.com/customise/db/extension/topfiveext/ the 1.0.4 version is still proposed for phpBB 3.1.x and at the same time, here https://github.com/rmcgirr83/phpBB-3.1-topfive/blob/master/composer.json file notices that the 1.1.1 version can be used with 3.1.x branch of phpBB:

```
		"soft-require": {
			"phpbb/phpbb": ">=3.1.2"
```

**Comment by rmcgirr83** [comment]
It can be used for either.
